# Generated by Django 5.1 on 2024-08-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dojf2qfyl/image/upload/v1724965652/no_image_mvrwpr.avif', upload_to='images/'),
        ),
    ]
