# Generated by Django 5.1 on 2024-08-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('trees', 'Trees'), ('animals', 'Animals'), ('mountains', 'Mountains'), ('water', 'Water'), ('places', 'Places'), ('cities', 'Cities')], default='normal', max_length=32),
        ),
    ]
